### ISSUE TITLE
not extracting .scp file

### ISSUE THREAD

**Issue by Vento5886** [sevenc-nanashi/scp-converter#2]
here's the log:

Started
Unzipping original SCP...

== Processing files
- Processing sonolus/repository/SkinThumbnail/24faf30cc2e0d0f51aeca3815ef523306b627289
is normal data file, sanitizing its name
An error occurred:
SyntaxError: Unexpected token '�', "�PNG

"... is not valid JSON

**Comment by sevenc-nanashi** [comment]
This tool converts scp **before 0.6.0 (0.5.x)** to 0.6.x, Not 0.6.x to 0.7.x.
